/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/contents/": {
    /** Create Content */
    post: operations["create_content_contents__post"];
  };
  "/contents/{content_id}": {
    /** Get Content */
    get: operations["get_content_contents__content_id__get"];
    /** Update Content */
    put: operations["update_content_contents__content_id__put"];
    /** Delete Content */
    delete: operations["delete_content_contents__content_id__delete"];
  };
  "/contents/parent/{user_id}/{parent_content_id}": {
    /** Get Contents By Parent Id */
    get: operations["get_contents_by_parent_id_contents_parent__user_id___parent_content_id__get"];
  };
  "/contents/parent/{user_id}": {
    /** Get Contents By Parent Id */
    get: operations["get_contents_by_parent_id_contents_parent__user_id__get"];
  };
  "/contents/folders/{user_id}/{parent_content_id}": {
    /** Get Folders By User Id And Parent Content Id */
    get: operations["get_folders_by_user_id_and_parent_content_id_contents_folders__user_id___parent_content_id__get"];
  };
  "/contents/folders/{user_id}": {
    /** Get Root Folders By User Id */
    get: operations["get_root_folders_by_user_id_contents_folders__user_id__get"];
  };
  "/users/": {
    /** Create User */
    post: operations["create_user_users__post"];
  };
  "/users/{user_id}": {
    /** Update User */
    put: operations["update_user_users__user_id__put"];
  };
  "/users/{telegram_id}": {
    /** Get User By Telegram Id */
    get: operations["get_user_by_telegram_id_users__telegram_id__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** ContentCreate */
    ContentCreate: {
      /** Title */
      title: string;
      /** Type */
      type: number;
      /** Parent Content Id */
      parent_content_id?: number | null;
      /** User Id */
      user_id: number;
      /** Tg Chat Id */
      tg_chat_id?: number | null;
      /** Tg Message Id */
      tg_message_id?: number | null;
      /** Body */
      body?: string | null;
      /** Attachment */
      attachment?: number | null;
    };
    /** ContentRead */
    ContentRead: {
      /** Title */
      title: string;
      /** Type */
      type: number;
      /** Parent Content Id */
      parent_content_id?: number | null;
      /** User Id */
      user_id: number;
      /** Tg Chat Id */
      tg_chat_id?: number | null;
      /** Tg Message Id */
      tg_message_id?: number | null;
      /** Body */
      body?: string | null;
      /** Attachment */
      attachment?: number | null;
      /** Id */
      id: number;
    };
    /** ContentUpdate */
    ContentUpdate: {
      /** Title */
      title: string;
      /** Type */
      type: number;
      /** Parent Content Id */
      parent_content_id?: number | null;
      /** User Id */
      user_id: number;
      /** Tg Chat Id */
      tg_chat_id?: number | null;
      /** Tg Message Id */
      tg_message_id?: number | null;
      /** Body */
      body?: string | null;
      /** Attachment */
      attachment?: number | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** UserCreate */
    UserCreate: {
      /** Telegram Id */
      telegram_id: number;
    };
    /** UserRead */
    UserRead: {
      /** Telegram Id */
      telegram_id: number;
    };
    /** UserUpdate */
    UserUpdate: {
      /** Telegram Id */
      telegram_id: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Create Content */
  create_content_contents__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ContentCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ContentRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Content */
  get_content_contents__content_id__get: {
    parameters: {
      path: {
        content_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ContentRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Content */
  update_content_contents__content_id__put: {
    parameters: {
      path: {
        content_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ContentUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ContentRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Content */
  delete_content_contents__content_id__delete: {
    parameters: {
      path: {
        content_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ContentRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Contents By Parent Id */
  get_contents_by_parent_id_contents_parent__user_id___parent_content_id__get: {
    parameters: {
      path: {
        user_id: number;
        parent_content_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ContentRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Contents By Parent Id */
  get_contents_by_parent_id_contents_parent__user_id__get: {
    parameters: {
      path: {
        user_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ContentRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Folders By User Id And Parent Content Id */
  get_folders_by_user_id_and_parent_content_id_contents_folders__user_id___parent_content_id__get: {
    parameters: {
      path: {
        user_id: number;
        parent_content_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ContentRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Root Folders By User Id */
  get_root_folders_by_user_id_contents_folders__user_id__get: {
    parameters: {
      path: {
        user_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ContentRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create User */
  create_user_users__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update User */
  update_user_users__user_id__put: {
    parameters: {
      path: {
        user_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get User By Telegram Id */
  get_user_by_telegram_id_users__telegram_id__get: {
    parameters: {
      path: {
        telegram_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
